### ISSUE TITLE
Serimi >> execution error

### ISSUE THREAD

**Issue by Tamouze** [samuraraujo/SERIMI-RDF-Interlinking#3]
Dear Mr Samuraraujo,

Im trying to use SERIMI. I uploaded two RDF datasets (Restaurant from OAEI2010). I put the proper  http://dbpedia.org as Named Graph IRI for both datasets. When i execute the following command to interlink the restaurant instances: 
Commande:
ruby serimi.rb -s   http://dbpedia.org/sparql?default-graph-uri=http://dbpedia.org -t http://dbpedia.org/sparql?default-graph-uri=http://dbpedia.org -c http://dbpedia.org/restaurant

i get the following errors:
c:/SERIMI-RDF-Interlinking-master/active_rdf/lib/active_rdf/objectmanager/bnode
rb:1: uninitialized constant RDFS (NameError)
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`require'
        from c:/SERIMI-RDF-Interlinking-master/active_rdf/lib/active_rdf.rb:30
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`require'
        from c:/SERIMI-RDF-Interlinking-master/active_rdf/lib/active_rdf/object
anager/object_manager.rb:1
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`require'
        from c:/SERIMI-RDF-Interlinking-master/active_rdf/lib/active_rdf/object
anager/resource.rb:4
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`gem_original_require'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in
`require'
        from ./active_rdf/lib/active_rdf.rb:29
        from ./initializer.rb:5:in `require'
        from ./initializer.rb:5
        from ./serimi_class.rb:5:in`require'
        from ./serimi_class.rb:5
        from serimi.rb:124:in `require'
        from serimi.rb:124

Please can you help me to resolve these errors?

Thanks you

**Comment by samuraraujo** [comment]
Hi, could you please send me the commands:

rvm list
gem list

The problem is due to wrong versions of gems or ruby. 
You should install exactly what mentioned in the documentation.

I will try to help you to solve it.
Best,
Samur

**Comment by Tamouze** [comment]
Dear Mr Araujo,

Thank you in advance for your help. The answers of :
1- rvm -v is :  
 ali@ali-Not-Specified:~$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

2- ruby -v is:
 ali@ali-Not-Specified:~$ ruby -v
ruby 1.8.7 (2014-01-28 patchlevel 376) [x86_64-linux]

3- jruby -v is: 
ali@ali-Not-Specified:~$ jruby -v
jruby 1.5.6 (ruby 1.8.7 patchlevel 249) (2014-02-03 6586) (OpenJDK 64-Bit Server VM 1.7.0_79) [amd64-java]

4- gem list is:
 actionmailer (2.3.2)
actionpack (2.3.2)
activerecord (2.3.2)
activeresource (2.3.2)
activesupport (2.3.2)
amatch (0.2.5)
bouncy-castle-java (1.5.0146.1)
bundler-unload (1.0.2)
elasticsearch (1.0.12)
elasticsearch-api (1.0.12)
elasticsearch-transport (1.0.12)
executable-hooks (1.3.2)
faraday (0.9.1)
fastthread (1.0.7)
gem-wrappers (1.2.7)
jruby-openssl (0.7.4)
json (1.5.1)
multi_json (1.11.2)
multipart-post (2.0.0)
OptionParser (0.5.1)
patron (0.4.9)
rails (2.3.2)
rake (10.4.2, 0.8.7)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sources (0.0.1)
text (0.2.0)
Text (1.1.2)
uuidtools (1.0.7)
v (0.1.1)
xml-object (0.9.93)
yajl-ruby (0.8.2)

Concerning the gems:
1- elasticsearch (0.0.0): i cant install by the command:  gem install elasticsearch -v=0.0.0 ---- i get the following error:
ERROR:  Could not find a valid gem 'elasticsearch' (= 0.0.0) in any repository
ERROR:  Possible alternatives: elasticsearch

2- jruby launcher 1.0.7-java: i cant install by the command: gem install jruby-launcher 1.0.7-java---- i get the following error:
ERROR:  Could not find a valid gem 'jruby-launcher' (>= 0), here is why:
          Found jruby-launcher (1.1.1), but was for platform java

Im working on Ubuntu:
Distributor ID:    Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:    trusty

Best Regards,

**Comment by samuraraujo** [comment]
Dear Tamouze, I have very limited time to help you.

Try to use this version:

https://github.com/samuraraujo/SondaSerimi

I cannot help to debug it at the moment.

Best,
Samur
